export const PVP_SOCKET = "PVP SOCKET"

export const PLAYER_SOCKET = {
    CREATE_ROOM: "PLAYER CREATE ROOM",
    JOIN_ROOM: "PLAYER JOIN ROOM",
    SELECT_UNIT: "PLAYER SELECT UNIT",
    SELECT_ABILITY: "PLAYER SELECT ABILITY",
    ATTACK: "PLAYER ATTACK",
    CHANGE_TURN: "CHANGE_TURN",
    FINISHED: "FINISHED",
}

export const UNIT_SOCKET = {
    
    ATTACK: "UNIT ATTACK",
    
}